"commit_message": "Add(lang): New translations on %locale_with_underscore% (%original_file_name%)"
"append_commit_message": false

files:
  - source: /src/main/resources/assets/languages/en_US.json
    translation: /src/main/resources/assets/languages/%locale_with_underscore%.json
